version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    restart: always

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
    restart: always

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
    restart: always

  questiongenerationservice:
      container_name: questiongenerationservice-${teamname:-defaultASW}
      image: ghcr.io/arquisoft/wiq_es3b/questiongenerationservice:latest
      profiles: ["dev", "prod"]
      build: ./question_generator
      ports:
        - "8003:8003"
      networks:
        - mynetwork
      environment:
        QUESTIONS_SERVICE_URL: http://questionservice:8004
        AUTH_SERVICE_URL: http://authservice:8002
      restart: always
  
  questionservice:
    container_name: questionservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/questionservice:latest
    profiles: ["dev", "prod"]
    build: ./questionservice
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questionsdb
    restart: always

  gameservice:
    container_name: gameservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/gameservice:latest
    profiles: ["dev", "prod"]
    build: ./gameservice
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/gamesdb
      USER_SERVICE_URL: http://userservice:8001
    restart: always
  friendsservice:
    container_name: friendsservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/friendsservice:latest
    profiles: ["dev", "prod"]
    build: ./users/friendsservice
    depends_on:
      - mongodb
    ports:
      - "8006:8006"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/friendsdb
      USER_SERVICE_URL: http://userservice:8001
    restart: always

  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - questiongenerationservice
      - questionservice
      - gameservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      QUESTION_GENERATION_SERVICE_URL: http://questiongenerationservice:8003
      QUESTIONS_SERVICE_URL: http://questionservice:8004
      GAME_SERVICE_URL: http://gameservice:8005
      FRIENDS_SERVICE_URL: http://friendsservice:8006
    restart: always

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es3b/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"
    environment:
      GATEWAY_SERVICE_URL: http://gatewayservice:8000
    restart: always
    #volumes:
      #- ./webapp:/app
    

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev", "prod"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev", "prod"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./grafana_admin_password:/run/secrets/grafana_admin_password
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
