ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
---

=== Contents
==== Scope and context

This project aims to develop a quiz game.
The main constraints are developing the game as a web app and using Wikidata to obtain the questions and answers.

---

=== Business Context

[role="arc42help"]

==== Contents

* *Users:* They interact directly with the application through the user interface provided by the frontend using React, HTML, CSS, and JavaScript.
* *Wikidata API:* The application communicates with the Wikidata service to obtain questions and answers related to different topics. Requests are made using the HTTP protocol, and response data is received in JSON format.

---

==== Motivation

Regarding the information exchanged with the application, it will require having a registered account to play, and it will also exchange information with a MongoDB database and Wikidata itself to obtain the questions.

---

==== Form

|===

| *Quiz Game* | *Comunication Partners* | *Inputs* | *Outputs*
| Users | User Interface | User answers | Game questions
| Wikidata API | API Service | Question requests | JSON Responses

|===

---

==== Context diagram

[plantuml, "context", png]
----
@startuml
component "App" as app
:User: -> [app]: Answer question
[app] -> :User: Return result
database DB
[app] -> DB: Ask for question
DB -> [app]: Return question
component "WikiData" as wd
[app] --> wd: Ask for keyword
wd --> [app]: Return keyword
@enduml
----

---

=== Technical Context

[role="arc42help"]

==== Contents

* *HTTP Channel:* The application uses the HTTP protocol to communicate with the Wikidata API service.
* *MongoDB Data Channel:* Interactions with the MongoDB database allow for storing and retrieving questions and answers.

---

==== Deployment diagram

[plantuml, "deployment", png]
----
@startuml
node "Application Server" as app
node "DB Server" as db {
    artifact "MongoDB Server"
}
node "Wikidata" as w
node "Interface" as i
app - db
app -- w
app -- i
@enduml
----
