ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View
=== Login

For the login, the app shows the login view, which asks the user for his username and his password.

Then, the app does a login request to the users microservice, which redirect the user to the identity provider, which handles the authentication.

If the login is succesfully, the app shows the different options of the game.
In case the login isn't succesfully, a warning message is shown.

[plantuml,"sequencediagram-login",png] 
----
actor User as u
participant "Web App" as w
participant "User Microservice" as um
activate w 
w -> w: Show Login View 
u -> w: Chooses Identity 
w -> um: Requests login 
deactivate w 
activate um
um -> um: Redirects to the provider login form 
um --> u: Asks for credentials 
deactivate um
activate u
u -> um: Logs in 
deactivate u 
activate um
um --> um: Provides session information 
um --> w: Provides session ID 
deactivate um
activate w 
w -> w: Show Game View
deactivate um
----
=== Game

When the user starts a game, the app generates a question and request the correct answer to the WikiData API. When the user choose a posible answer, the app checks if it is the correct answer. Then, this process is repeated until the end of the game.  

[plantuml,"sequencediagram-game",png]
----
actor User as user
participant WebApp as app
participant GameMS as gameMS
participant WikiDataAPI as api

activate app

user -> app: Start game
app -> gameMS: Generate question
gameMS -> api: Request correct answer\nfor the generated question
api --> gameMS: Correct answer
gameMS -> app: 
app -> user: Show question and options

loop Until end of the game
    user -> app: Choose possible answer
    app -> gameMS: Verify answer\nselected by the user
    gameMS --> app: Correct or incorrect answer
    app -> user: Show result\nand current score
end

user -> app: Finish game
app --> user: Show final score

deactivate app
----
=== Ranking
In this view, the user can watch different rankings:

- Ordered by accuracy percentage
- Ordered by number of questions answered correctly
- Ordered by quantity of game rounds

[plantuml,"sequencediagram-ranking",png]
----
actor User as user
participant RankingMS as MS
participant MongoDB as db

activate MS

user -> MS: Request ranking
MS -> db: Asks for the ranking
db -> MS: Gives the ranking with the best
MS -> user: Shows the ranking


deactivate MS
----
=== History
In this view, the user can watch this options about his past games:

- Number of games played
- Best times
- Correct/incorrect questions

[plantuml,"sequencediagram-history",png]
----
actor User as user
participant HistoryMS as MS
participant MongoDB as db

activate MS

user -> MS: Request history
MS -> db: Asks for the history
db -> MS: Gives the user's history
MS -> user: Shows the history

deactivate MS
----
