ifndef::imagesdir[:imagesdir: ../images]

[[section-glossary]]
== Glossary

[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms


.Form

A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.


.Further Information

See https://docs.arc42.org/section-12/[Glossary] in the arc42 documentation.

****

[cols="e,2e" options="header"]
|===
|Term |Definition

|React
|JavScript library, we make use of this User Interface library on the front-end

|Docker
|We use it to deploy applications within virtual containers

|Node.js
|JavaScript runtime environment, we make use of this on the back-end

|GitHub
|Portal used to host the application code and documentation
|===
