openapi: 3.0.0
info:
  title: Friends Service API
  version: 1.0.0
servers:
  - url: http://localhost:8006
  - url: http://friendsservice:8006
paths:
  /friends/{username}:
    get:
      summary: Get friends of a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: '#/components/schemas/Friend'
              example:
                  username: 'user1'
                  friends: ['friend1', 'friend2']
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /friends:
    post:
      summary: Add a friend to a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                friend:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  friends:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /friends/{username}/{friend_username}:
    delete:
      summary: Delete a friend from a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: friend_username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  friends:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Friend: 
      type: object
      properties:
        username: 
          type: string
        friends:
          type: array
          items:
            type: string