openapi: 3.0.0
info:
  title: Question Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8004'
  - url: http://questionservice:8004
paths:
  /questions:
    post:
      summary: Add a new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '200':
          description: Question added successfully
        '400':
          description: Missing required fields
        '500':
          description: Error occurred while adding question
  /api/info/questions:
    get:
      summary: Get questions information
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: Filter by question ID
        - in: query
          name: user
          schema:
            type: string
          description: Filter by user
        - in: query
          name: category
          schema:
            type: string
          description: Filter by category
      responses:
        '200':
          description: Questions information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  questions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Question'
                    example:
                      - id: 1
                        user: john_doe
                        category: science
                        question: What is the capital of France?
                        correct: Paris
                        incorrects:
                          - London
                          - Berlin
                        generationDate: '2022-10-01T10:00:00Z'
                      - id: 2
                        user: john_doe
                        category: history
                        question: Who was the first president of the United States?
                        correct: George Washington
                        incorrects:
                          - Abraham Lincoln
                          - Thomas Jefferson
                        generationDate: '2022-10-02T14:30:00Z'
        '404':
          description: No questions found
        '500':
          description: Error occurred while retrieving questions information
components:
  schemas:
    Question:
      type: object
      properties:
        question:
          type: string
        correct:
          type: string
        incorrects:
          type: array
          items:
            type: string
        user:
          type: string
        category:
          type: string